steps:
- name: 'mcr.microsoft.com/dotnet/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: '/'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - "-c"
    - |
        dotnet publish -c Release
        cp Dockerfile ./bin/Release/netcoreapp3.1/publish/
  dir: '/'
timeout: '1600s'
