steps:
- name: 'mcr.microsoft.com/dotnet/sdk:3.1'
  entrypoint: 'dotnet'
  args: [ 'publish', '-c', 'Release' ]
  dir: 'BetterTrucksDeployTest4/'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
    - "-c"
    - |
        dotnet publish -c Release
        cp /BetterTrucksDeployTest4/Dockerfile ./bin/Release/netcoreapp3.1/publish/
  dir: 'BetterTrucksDeployTest4/'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args: ['-c', 'gcloud app deploy ./bin/Release/netcoreapp3.1/publish/app.yaml']
  dir: 'BetterTrucksDeployTest4/'
timeout: '1600s'
